name: .NET

on:
  workflow_dispatch:
  schedule:
    - cron: "30 00 * * *"
  push:
    branches:
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Run
      run: dotnet run --project HajdukCal.Console/HajdukCal.Console.csproj
    - name: Delete old release asset
      uses: mknejp/delete-release-assets@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: 1.0.0
        assets: hajduk_cal.ics
        fail-if-no-assets: false
    - name: Upload new release asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: https://uploads.github.com/repos/antoniaelek/HajdukCal/releases/58292780/assets{?name,label}
        asset_path: hajduk_cal.ics
        asset_name: hajduk_cal.ics
        asset_content_type: application/zip
